/**
 * FAQ Data for Digital Health Platforms
 * Deep dive into API integration, white-labeling, scalability, technical architecture
 */

export const digitalHealthPlatformsFAQs = [
  // API Integration & Technical Setup
  {
    question: "How long does it take to integrate Labstack APIs into our platform?",
    answer: "Integration timeline by complexity: (1) Quick start—2-4 hours using pre-built SDKs (JavaScript, Python, PHP, Java) with sandbox testing, (2) Basic production integration—1-2 weeks for core booking APIs (diagnostics, consultations, pharmacy) with standard authentication and webhooks, (3) Full white-label customization—2-3 weeks including custom branding, domain setup, SSO integration, callback URLs, (4) Complex enterprise integration—4-6 weeks for legacy system compatibility, custom workflows, HRMS integration, multi-tenant architecture. Much faster than building in-house (6-12 months) or onboarding multiple vendor APIs separately. Technical requirements: REST API knowledge, JSON handling, webhook endpoints, basic frontend for UI. We provide: Comprehensive API documentation, Postman collections, sandbox environment with test data, code samples in 5+ languages, dedicated integration engineer for enterprise clients, developer Slack channel for real-time support."
  },
  {
    question: "Do you provide embeddable widgets or only backend APIs?",
    answer: "Multiple integration options: (1) RESTful APIs—programmatic control over entire workflow, build your own UI, maximum flexibility, ideal for platforms with established design systems, (2) Embeddable widgets—drop-in JavaScript widgets for booking diagnostics, consultations, pharmacy with pre-built UI, customizable colors/fonts, works like Google Maps embed, (3) Pre-built React/Vue components—npm packages for modern web apps, (4) Mobile SDKs—iOS (Swift) and Android (Kotlin) native SDKs for app integration, (5) iFrame integration—simplest option, embed complete booking flow as iFrame on your page, minimal coding, (6) WhatsApp bot—conversational booking via WhatsApp Business API for non-app users. Choose based on: Development resources (API = more control but more work, widgets = faster but less customization), user experience needs, time to market urgency. Most platforms start with widgets for MVP (2-3 days integration), migrate to APIs later for full customization (2-3 weeks)."
  },
  {
    question: "Can we use our own UI and call your APIs in the background (headless)?",
    answer: "Absolutely, headless architecture is our strength: (1) Complete frontend control—design booking flows, results display, tracking dashboards in your style, (2) API handles backend—eligibility verification, provider coordination, fulfillment, quality control, billing, (3) Webhook notifications—real-time updates to your system when booking confirmed, sample collected, reports ready, delivery completed, (4) Custom business logic—implement your own rules (discount codes, member limits, approval workflows) on top of our APIs, (5) Multi-platform reuse—same backend APIs power your web app, iOS app, Android app, call center dashboard. Common for: Established healthtech platforms with design systems (Practo, 1mg style apps), insurance companies wanting branded member portals, large corporates with custom HRMS/benefits portals, white-label resellers serving multiple clients. API-first approach means zero UI lock-in—you control every pixel of user experience while we handle complex healthcare operations invisible to users."
  },
  {
    question: "What if we want to use our contracted providers alongside Labstack's network?",
    answer: "Hybrid network model supported: (1) Dual network mode—run your providers parallel to Labstack network, routing logic determines which to use based on location, availability, pricing, (2) Provider onboarding—we onboard your contracted labs/hospitals/pharmacies onto our platform, they use our tech for fulfillment, (3) Unified operations—single dashboard to manage both networks, consistent SLA monitoring, quality standards, reconciliation, (4) Intelligent routing—if your provider unavailable, automatic failover to Labstack network ensuring zero service disruption, (5) Load balancing—distribute orders across providers based on capacity, performance, cost optimization, (6) White-label for all—both your providers and ours operate under your brand, users don't see the difference. Use cases: (1) Insurance companies with empaneled hospital networks want to expand OPD coverage, (2) Pharmacy chains want to fill gaps in geographies where they lack presence, (3) Corporate wellness programs want to use company clinic + external network. Technical: Single API, provider_preference parameter determines routing, graceful fallback logic built-in."
  },
  {
    question: "How does complete white-labeling work across all touchpoints?",
    answer: "End-to-end brand control: (1) Member-facing UI—your logo, brand colors, typography, design language across booking flows, reports, tracking pages, (2) Custom domain—wellness.yourcompany.com or health.yourcompany.com (not labstack.in), (3) Communications—all SMS, emails, WhatsApp, push notifications sent from your brand name with your templates, (4) Reports—diagnostic reports, prescriptions carry your header/footer, branding elements, (5) Customer support—phone numbers show your company, support agents trained to represent your brand, (6) Legal documents—T&Cs, privacy policy, consent forms under your entity name, (7) Provider instructions—labs/phlebotomists/delivery staff instructed to mention your brand to patients. Labstack completely invisible: (1) No 'Powered by Labstack' footer, (2) Provider agreements confidential, (3) Payment processing under your name, (4) App store listings as your app, (5) Domain WHOIS shows your company. White-label vs co-brand: White-label = 100% your brand (₹2-5L setup + ₹50K-1L monthly), Co-brand = 'Powered by Labstack' allowed (lower cost). Most enterprise clients choose white-label for premium positioning."
  },
  
  // Scalability & Performance
  {
    question: "What is your API uptime SLA and what happens during downtime?",
    answer: "Reliability guarantees: (1) 99.5% uptime SLA—< 4 hours downtime per month, (2) Redundant architecture—multi-region AWS deployment, automatic failover if one region down, (3) Load balancing—horizontal scaling handles traffic spikes (festivals, health camps, insurance enrollment periods), (4) Database replication—real-time data sync across regions, no data loss during outages, (5) Queued processing—if API temporarily down, requests queued and processed when system recovers (max 4-hour queue), (6) Graceful degradation—non-critical features disabled during partial outages, core booking continues. Downtime handling: (1) Real-time status page (status.labstack.in)—current system health visible to all partners, (2) Incident notifications—SMS/email/Slack alerts when downtime detected + when resolved, (3) SLA credits—if we breach 99.5% uptime in a month, 5% monthly fee credited back automatically, (4) Post-mortem—detailed incident report within 48 hours explaining root cause and prevention measures. Typical causes: Planned maintenance (announced 7 days prior, done at 2-4 AM IST), cloud provider issues (rare, auto-failed over), DDoS attacks (mitigated via Cloudflare). Monitoring: 24/7 NOC team, automated alerts, < 5 minute response time for critical issues."
  },
  {
    question: "How does pricing scale as our user base grows from 10K to 1M users?",
    answer: "Volume-based pricing model: (1) Startup tier (0-10K users)—standard rates, no setup fee, pay-as-you-go, ₹150-200 per transaction, (2) Growth tier (10K-100K users)—10% volume discount, dedicated account manager, ₹135-180 per transaction, (3) Scale tier (100K-500K users)—15-20% discount, custom SLA, priority support, ₹120-160 per transaction, (4) Enterprise tier (500K+ users)—20-30% discount, negotiated rates, committed capacity, ₹105-140 per transaction, custom contracts. No minimum commitments in early tiers—pay only for completed transactions. Billing: (1) Postpaid monthly invoicing—use services, billed at month-end based on actual usage, (2) Prepaid credits—buy ₹5L-10L credits upfront for additional 3-5% discount, (3) Committed use discounts—commit to ₹50L-1Cr annual spend, get 15-25% discount upfront. Price transparency: (1) Per-transaction rates—diagnostic test ₹X, consultation ₹Y, pharmacy order ₹Z, (2) No hidden fees—what you see is what you pay, (3) Predictable—historical usage data helps forecast monthly costs. Inflation protection: Annual rate review, maximum 5% increase per year. Enterprise clients negotiate multi-year rate locks."
  },
  {
    question: "Can we handle 10,000+ concurrent users during peak times like open enrollment?",
    answer: "Built for scale: (1) Auto-scaling infrastructure—AWS/GCP automatically adds servers during traffic spikes, tested up to 50,000 concurrent users, (2) Rate limiting—prevent single client from overwhelming system, configurable limits per API key, (3) Caching—frequently accessed data (provider lists, pin code coverage) cached for faster response, (4) CDN delivery—static assets served via CloudFront for global low-latency access, (5) Database optimization—read replicas for queries, indexed for sub-second response times. Peak traffic handling: (1) Pre-event scaling—inform us 1 week before expected spike (health camps, enrollment drives, marketing campaigns), we pre-provision extra capacity, (2) Load testing—we test your integration with simulated 10K concurrent users before launch, (3) Monitoring—real-time dashboards track API response times, error rates, alert if degradation. Real-world examples: (1) Insurance open enrollment—handled 30,000 policy activations in 3 days, 8,000 concurrent bookings during peak hours without issues, (2) Corporate health camp—5,000 employee registrations in 2 hours, (3) Government health scheme—200,000 beneficiaries onboarded over 1 month. Performance benchmarks: < 200ms API response time (p95), < 0.01% error rate during normal operation, < 0.1% during peak spikes."
  },
  
  // Data & Security
  {
    question: "How do you handle data privacy, security, and regulatory compliance?",
    answer: "Healthcare-grade security: (1) Encryption—AES-256 at rest, TLS 1.3 in transit, end-to-end encryption for sensitive data (health records, prescriptions), (2) Access controls—role-based permissions (RBAC), principle of least privilege, MFA for admin access, (3) Audit logs—every API call, data access, modification logged with timestamp, user, IP address, immutable for 7 years, (4) Data residency—all health data stored in India (compliance with data localization), multiple backup locations, (5) Regular security audits—quarterly penetration testing by third-party firms, annual vulnerability assessments. Compliance: (1) IT Act 2000—fully compliant with Indian cybersecurity laws, (2) DISHA guidelines—adherence to digital health data protection norms, (3) Telemedicine Practice Guidelines—compliance with MCI/NDHM regulations for teleconsult, (4) SOC 2 Type II—in progress, expected completion Q3 2025, (5) ISO 27001—information security management certification planned 2025. Data protection: (1) Data anonymization—PII stripped for analytics/reporting, (2) Right to deletion—users can request data deletion, executed within 30 days, (3) Breach notification—inform affected parties within 72 hours if breach detected. Partner controls: API keys with IP whitelisting, webhook signature verification, rate limiting prevents data scraping."
  },
  {
    question: "Can we export or own the patient data generated through your platform?",
    answer: "Complete data ownership: (1) You own the data—all patient health records, booking history, reports belong to you legally, we are data processor on your behalf, (2) API export—real-time access to all data via APIs, pull whenever needed, (3) Bulk export—CSV/JSON exports of historical data, scheduled daily/weekly/monthly, (4) Database replication—for enterprise clients, we can replicate data to your own database in real-time via AWS DMS or Fivetran, (5) Data portability—if you decide to leave, full data dump provided in standard formats (HL7 FHIR, CSV, JSON) within 30 days, (6) Zero lock-in—your data, your users, you can migrate anytime. Data access: (1) Via dashboard—UI to view/download data, (2) Via API—programmatic access for integration with analytics tools (Tableau, Power BI, Google Data Studio), (3) Via webhooks—real-time streaming of events to your data warehouse (Snowflake, BigQuery, Redshift). Retention: (1) Active contract—data retained for duration of partnership, (2) Post-termination—data retained for 90 days for transition, then deleted as per agreement unless longer retention requested. Privacy commitment: We never sell, share, or use your data for purposes beyond agreed service delivery. Auditable: Access logs show exactly who accessed what data when."
  },
  
  // Support & Partnership
  {
    question: "Can we handle customer support ourselves or do you manage it?",
    answer: "Flexible support model: (1) Partner-managed—you handle all customer queries, we provide ops console for your support team to manage bookings, reschedule, cancel, track issues, resolve exceptions, (2) Labstack-managed—we handle customer support (phone, email, chat), branded as your company, agents trained on your brand voice, no patient knows Labstack exists, (3) Hybrid—you handle Tier-1 (FAQs, booking help), we handle Tier-2/3 (operational issues, provider coordination, escalations), (4) White-label BPO—we operate support center that appears to be yours, including your phone numbers, email domain, scripts. Training provided: (1) Ops console walkthrough—how to reschedule, refund, track status, (2) Common scenarios—failed sample collection, delayed reports, wrong medicines delivered, (3) Escalation matrix—when to involve Labstack backend team, (4) Quality standards—response time expectations, customer satisfaction targets. Support infrastructure: (1) Ops dashboard—see all bookings, track status, take actions, (2) Knowledge base—internal wiki with solutions to common issues, (3) Ticketing system—raise issues to Labstack, track resolution, SLA monitoring, (4) Analytics—support volume trends, resolution times, satisfaction scores. Most platforms: Start with Labstack-managed support (faster launch, learn customer issues), transition to partner-managed after 6-12 months (cost savings, brand control)."
  },
  {
    question: "Do you support international expansion outside India?",
    answer: "India-first, expanding globally: (1) Current coverage—comprehensive across India: 9,000+ pincodes, 600+ cities for diagnostics, consultations, pharmacy, (2) Southeast Asia pipeline—building capabilities for Bangladesh (launch Q4 2025), Sri Lanka (Q1 2026), Myanmar, Nepal (2026), (3) Middle East plans—UAE, Saudi Arabia, Qatar (2026-2027) where large Indian diaspora creates familiar market dynamics, (4) Africa exploration—Kenya, Nigeria, South Africa (2027+) as next expansion targets. Early access program: Design partners get priority access to new geographies, participate in beta testing, provide feedback on localization. International considerations: (1) Regulatory compliance—healthcare regulations vary by country, we handle local licensing, privacy laws, (2) Local networks—onboard providers in target countries, adapt to local healthcare delivery models, (3) Currency handling—multi-currency pricing, local payment methods (M-Pesa for Africa, regional banks), (4) Language localization—beyond English, local languages for each market. Current recommendation: If you need international NOW, we can help with RFPs, vendor shortlists for other countries while you use Labstack for India. When we launch in your target geography, easy to consolidate onto single platform. Beta access: Express interest to [email protected], we prioritize partners for geography-specific betas."
  },
  {
    question: "What SDKs and programming languages do you support?",
    answer: "Comprehensive developer tools: (1) Official SDKs—JavaScript/TypeScript (npm package), Python (pip package), PHP (Composer), Java (Maven), maintained by our team with regular updates, (2) Community SDKs—Ruby, Go, .NET (C#), React Native contributed by developer community, available on GitHub, (3) Mobile native—iOS Swift SDK (CocoaPods), Android Kotlin SDK (Gradle), (4) RESTful APIs—work with ANY language/framework (Node.js, Django, Laravel, Spring Boot, Rails, .NET), (5) GraphQL—beta access available for clients preferring GraphQL over REST. SDK features: (1) Authentication handling—automatic token refresh, error retries, (2) Type safety—TypeScript definitions, Python type hints, strong typing in Java, (3) Async support—promises in JS, async/await in Python, RxJava for Android, (4) Error handling—structured errors with actionable messages, (5) Logging—request/response logging for debugging. Resources: (1) GitHub repository—open-source SDKs with examples, (2) Postman collections—import and test all endpoints instantly, (3) OpenAPI/Swagger spec—auto-generate clients in your preferred language, (4) Code samples—complete working examples for common use cases, (5) Interactive API explorer—test APIs in browser without writing code. Developer community: Slack workspace (1,500+ developers), monthly office hours, hackathons, swag for contributors."
  },
  {
    question: "Can we run pilots in select cities before nationwide rollout?",
    answer: "Phased rollout fully supported: (1) City-based controls—enable services only in Mumbai, Delhi, Bangalore for first 3 months, (2) User cohort testing—pilot with 1,000 users before opening to 100,000, collect feedback, refine UX, (3) Service-specific rollout—launch diagnostics first (month 1), add consultations (month 2), pharmacy (month 3), (4) Geography expansion strategy—metros first (month 1-3), tier-2 cities (month 4-6), tier-3 (month 7+), measure unit economics at each stage. Pilot best practices: (1) Define success criteria upfront—target booking rates, satisfaction scores, cost per transaction, (2) Over-communicate—ensure pilot users understand it's beta, expect to report issues, (3) Rapid iteration—weekly updates based on feedback, fix bugs within 48 hours, (4) Dedicated support—assign integration engineer + customer success manager during pilot, (5) Metrics dashboards—track adoption, usage, issues daily, weekly review calls. Risk mitigation: Starting small reduces financial exposure, allows learning before scaling. Common pilot approach: (1) Internal employees first (100-500 people) for 2-4 weeks—dogfooding, (2) Friendly customer beta (1,000-5,000 users) for 1-2 months—real users, controlled environment, (3) Public launch—once confidence established. Geographic controls: API parameter `allowed_pincodes` limits service availability, easily expanded when ready. We've supported 50+ pilots with 95% proceeding to full rollout post-pilot."
  },
  
  // Advanced Use Cases
  {
    question: "Can we build marketplace features where users book directly from providers?",
    answer: "Marketplace mode enabled: (1) Provider selection—users see list of available labs/clinics/pharmacies with ratings, prices, distance, choose preferred one, (2) Dynamic pricing—providers set their own rates within platform ranges, surge pricing during peak times, (3) Reviews and ratings—users rate providers after service, influences future recommendations, (4) Direct provider interaction—users contact providers for questions, reschedule directly, (5) Revenue sharing—split transaction fees between platform and provider, configurable percentages. Platform controls: (1) Quality gates—only providers meeting quality standards appear in marketplace, (2) Demand shaping—algorithmically promote high-quality/low-cost providers, deprioritize underperformers, (3) Fraud prevention—monitor fake reviews, suspicious pricing, collusion, (4) Dispute resolution—standardized process for complaints, refunds, provider penalties. Use cases: (1) Diagnostics marketplace—users compare lab prices for same test, choose cheapest/nearest, (2) Doctor marketplace—book consultations with specific doctors by specialty/experience/ratings, (3) Pharmacy comparison—multiple pharmacies quote for prescription, user picks best price/delivery time. Technical: `marketplace_mode=true` flag in API, returns provider options instead of automatic assignment, user selection tracked for personalization. Complexity: More engineering for frontend UI, more operations for provider management vs our standard model (we assign best provider automatically). Choose marketplace if: User choice is core value prop, willing to invest in UX, can handle operations overhead."
  },
  {
    question: "How do you handle multi-tenancy for B2B2C platforms serving multiple clients?",
    answer: "Enterprise multi-tenant architecture: (1) Tenant isolation—each client gets separate database schema, data never co-mingled, (2) Branded experiences—each tenant has custom white-label (logo, colors, domain), end users see only their tenant's brand, (3) Tenant-specific configs—pricing, service inclusions, provider networks, SLAs customizable per tenant, (4) Unified billing—we bill you (platform owner) for all tenants, you bill individual tenants based on your revenue model, (5) Cross-tenant analytics—aggregate anonymized data across tenants for benchmarking, no PII shared. API design: (1) Tenant ID in every request—X-Tenant-ID header identifies which client, (2) Scoped API keys—keys tied to specific tenants, can't access other tenants' data, (3) Webhooks per tenant—different callback URLs for each tenant's events. Use cases: (1) Insurance brokers serving 50 corporate clients—each corporate sees only their employees' data, (2) B2B2C healthtech serving hospitals/clinics—each hospital white-labels for their patients, (3) White-label SaaS resellers—one platform, 20 reseller customers, each rebranded. Management tools: (1) Super-admin dashboard—manage all tenants from single interface, (2) Tenant provisioning—onboard new tenant in 5 minutes via API, (3) Resource allocation—set capacity limits per tenant to prevent one tenant monopolizing resources. Pricing: Enterprise plan with multi-tenancy ₹3-5L setup + usage fees across all tenants, volume discounts apply to total across all tenants."
  }
];
