/**
 * FAQ Data for Disease Management Programs
 * Deep dive into chronic care protocols, patient engagement, clinical outcomes
 */

export const diseaseManagementFAQs = [
  // Care Pathway Design & Implementation
  {
    question: "What chronic diseases can be managed through protocol-driven care pathways?",
    answer: "Comprehensive disease coverage: (1) Diabetes—Type 1, Type 2, prediabetes with HbA1c monitoring, retinopathy screening, foot care protocols, (2) Hypertension—BP monitoring, medication titration, lifestyle modifications, cardiovascular risk assessment, (3) Cardiac care—post-MI management, heart failure, arrhythmias with ECG, ECHO, lipid monitoring, (4) CKD (Chronic Kidney Disease)—creatinine tracking, dialysis coordination, transplant care, (5) COPD/Asthma—spirometry, inhaler technique, exacerbation management, (6) Cancer support—chemotherapy side effects, nutrition, pain management, palliative care, (7) Mental health—depression, anxiety, bipolar disorder with therapy + medication management, (8) Arthritis—pain management, physiotherapy, DMARDs monitoring. Also supports: Thyroid disorders, PCOS, osteoporosis, inflammatory bowel disease (IBD). Custom protocols available for niche conditions based on your patient population."
  },
  {
    question: "How do automated care pathways work end-to-end for diabetes patients?",
    answer: "Diabetes care journey example: (1) Enrollment—Patient registered with diagnosis, baseline HbA1c, current medications, (2) Initial assessment—Comprehensive health check (HbA1c, lipid profile, kidney function, eye screening), risk stratification (low/moderate/high risk), (3) Care plan assignment—Protocol-based plan: HbA1c every 3 months, fasting blood sugar monthly, annual eye exam, quarterly doctor review, (4) Automated scheduling—System auto-books tests based on protocol, sends reminders 3 days prior, confirms appointments, (5) Result monitoring—Abnormal HbA1c (>7%) triggers consult within 48 hours, medication adjustment recommendations, (6) Medication adherence—Pharmacy auto-refills metformin/insulin, tracks pickup/delivery, flags missed doses, (7) Lifestyle interventions—Nutrition coaching if BMI >25, exercise plan, educational content on diabetes management, (8) Escalation handling—HbA1c >9% triggers endocrinologist referral, hospitalization if needed. Entire pathway runs automatically—zero manual coordination."
  },
  {
    question: "Can I get structured health data instead of just PDF reports?",
    answer: "Digital-first data model: (1) Raw test values—numerical data (glucose: 126 mg/dL, HbA1c: 7.2%, BP: 140/90 mmHg) in JSON/API format, (2) Longitudinal tracking—time-series database stores every test result, consultation note, medication change, (3) Trend analysis—automated charts showing HbA1c progression over 6-12 months, BP control, weight trends, (4) Clinical decision support—algorithms flag deteriorating trends (HbA1c increasing 0.5% over 3 months → intensify treatment), (5) Interoperability—HL7 FHIR-compatible, integrates with EMRs, population health platforms, analytics tools, (6) Custom dashboards—build your own views of patient cohorts, risk stratification, outcome metrics. No more manual PDF parsing or data entry. Structured data enables: Predictive analytics, personalized care plans, automated risk scoring, research/reporting."
  },
  {
    question: "How do you ensure 90%+ patient adherence to care protocols?",
    answer: "Behavioral design for adherence: (1) Automated reminders—SMS/WhatsApp 3 days before test due, day before appointment, same-day reminder, (2) Convenience—home sample collection (no need to visit lab), teleconsult (no commute), medicine delivered (no pharmacy trip), (3) Friction reduction—one-click booking, no forms to fill, cashless if covered by insurance/employer, (4) Positive reinforcement—congratulatory messages for completing tests on time, badges for adherence streaks, (5) Escalation nudges—if patient misses appointment, care manager calls within 24 hours, understands barriers, resolves issues, (6) Family involvement—family members get notifications for critical patients (elderly, severe conditions), (7) Gamification—points for adherence, leaderboards, rewards (discounts on next test, wellness credits). Result: 90%+ test completion rates vs 60-70% for manual care programs. Non-adherence triggers human intervention—care managers reach out to understand why and resolve barriers."
  },
  {
    question: "What cities and areas are covered for comprehensive disease management services?",
    answer: "Nationwide coverage: (1) Diagnostics—9,000+ pincodes for home collection across metros (Mumbai, Delhi NCR, Bangalore, Pune, Hyderabad, Chennai, Kolkata), tier-2 cities (Indore, Jaipur, Lucknow, Coimbatore, Kochi, Nagpur, Visakhapatnam, Bhubaneswar, Chandigarh, Vadodara, Rajkot, Mysore, Mangalore, Nashik), and tier-3 cities (Ranchi, Raipur, Dehradun, Guntur, Vijayawada, Gorakhpur, Varanasi, Siliguri, Guwahati), (2) Consultations—teleconsult available 24/7 nationwide, in-person specialist clinics in 600+ cities, (3) Pharmacy—medicine delivery to 18,000+ pincodes including remote areas, cold chain for insulin/biologics, (4) Home care—nursing visits, physiotherapy, wound care available in metros and tier-2 cities. Same care protocol quality across all geographies—rural patient in Ranchi gets same HbA1c monitoring schedule as urban patient in Mumbai. Technology bridges geographic disparities."
  },
  
  // Clinical Outcomes & Monitoring
  {
    question: "What is the typical patient engagement rate in disease management programs?",
    answer: "Engagement benchmarks: (1) Enrollment—85-90% eligible patients agree to enroll when benefits explained properly, (2) Activation—75-80% complete initial health assessment within first month, (3) Active participation—65-75% of enrolled patients actively engage (complete tests, attend consults) over 6 months, (4) 12-month retention—70-75% remain active after first year vs 40-50% for manual programs, (5) Test completion—90%+ for automated reminder-driven protocols vs 60-70% manual, (6) Consultation adherence—80-85% attend scheduled follow-ups vs 50-60% manual. Varies by condition: Diabetes/hypertension programs (75-80% engagement), cancer support (85-90%, higher motivation), mental health (60-70%, stigma barriers), arthritis (70-75%). Age factor: 35-55 age highest engagement (80%+), 55-70 age (70-75%), 70+ age (60-65%, digital literacy barriers). Program longevity: 2.5-3x higher patient LTV compared to manual care due to sustained engagement."
  },
  {
    question: "Can you share clinical outcome improvements from disease management programs?",
    answer: "Measured health outcomes: (1) Diabetes—average HbA1c reduction of 0.8-1.2% over 6 months, 60-70% patients achieve target HbA1c <7%, (2) Hypertension—70-75% patients achieve BP control <140/90 mmHg within 3-4 months, (3) Hospitalization reduction—45-50% fewer hospitalizations for ambulatory-sensitive conditions (diabetes complications, hypertension emergencies, COPD exacerbations), (4) Emergency visits—40-45% reduction in ER visits due to proactive monitoring and early intervention, (5) Medication adherence—80-85% adherence to prescribed regimens vs 50-60% without structured programs, (6) Quality of life—30-40% improvement in patient-reported QoL scores, (7) Cost savings—₹8,000-12,000 per patient annually in avoided hospitalizations and complications. Outcomes tracked via: Pre-post comparison of clinical parameters, hospitalization claims data, patient surveys (SF-36, PHQ-9 for mental health), pharmacy refill rates. Transparent reporting quarterly to program sponsors (insurers, employers, government)."
  },
  {
    question: "How do you handle emergency situations flagged by test results?",
    answer: "Critical value management: (1) Auto-flagging—system detects critical values (HbA1c >12%, blood sugar >400 mg/dL, creatinine >3 mg/dL, severe anemia Hb <7 g/dL) within minutes of result availability, (2) Instant alerts—SMS/WhatsApp to patient, family, care manager, and assigned doctor simultaneously, (3) Escalation protocol—care manager calls patient within 1 hour, assesses symptoms, coordinates next steps, (4) Urgent consultation—doctor teleconsult scheduled within 2-4 hours or immediate ER referral if life-threatening, (5) Hospitalization coordination—if needed, coordinate with network hospitals, inform insurer for cashless approval, arrange ambulance if required, (6) Family notification—family members informed with patient consent, guidance on immediate actions, (7) Follow-up—post-crisis follow-up within 48 hours to ensure stabilization, medication adjustments, prevent recurrence. Full audit trail maintained—timestamp of alert, actions taken, personnel involved—for quality assurance and medicolegal protection. Response time benchmarks: Alert generation <5 minutes, care manager contact <60 minutes, doctor consultation <4 hours for critical cases."
  },
  
  // Technology & Integration
  {
    question: "Can I customize protocols for my specific patient population or clinical guidelines?",
    answer: "Fully configurable care protocols: (1) Test frequencies—define how often each test (HbA1c every 3 months vs 6 months based on control), (2) Consultation triggers—specify when to escalate (e.g., HbA1c increase >0.5% triggers endo referral), (3) Medication protocols—formulary preferences, generic substitution rules, titration algorithms, (4) Escalation rules—when to involve specialists, hospitalization criteria, family notification thresholds, (5) Care team workflows—roles of care managers, doctors, specialists, family in patient journey, (6) Patient segmentation—different protocols for low/moderate/high risk patients, age-based variations, comorbidity adjustments. Implementation: You provide clinical SOPs/guidelines → We translate into platform logic → Testing with pilot patients → Refinement → Full rollout. Common customizations: Insurance company wants IRDAI-compliant protocols, corporate wants cost-effective pathways, hospital wants evidence-based medicine alignment, government wants NDHM/ABDM integration. Configuration done via admin portal without code changes—adjust parameters, test frequencies, alert thresholds. Changes reflect in real-time across all enrolled patients."
  },
  {
    question: "Can I integrate Labstack with my EMR or care management software?",
    answer: "Bidirectional integration capabilities: (1) API-based—RESTful APIs for pushing care plans, pulling service completion data, syncing health records, (2) HL7/FHIR support—standard healthcare interoperability formats for EMR integration (Epic, Cerner, AllScripts, Practo Ray, HealthPlix), (3) Webhook notifications—real-time updates when test completed, consult done, critical value flagged, (4) Data export—scheduled batch exports (daily/weekly) in CSV, JSON, XML for legacy systems, (5) Custom connectors—we build custom integrations for popular platforms (Salesforce Health Cloud, eClinicalWorks, Meditech), (6) SSO integration—single sign-on so care managers don't need separate logins. Use cases: (1) Push care plans from EMR to Labstack for execution, (2) Pull completed test results back into EMR for doctor review, (3) Sync medication lists, allergy info, immunization records, (4) Trigger care interventions in Labstack based on EMR data (e.g., recent hospitalization → intensify monitoring). Integration timeline: 2-3 weeks for standard EMRs, 4-6 weeks for custom/legacy systems. Technical requirements: API documentation, test environment access, IT team collaboration."
  },
  {
    question: "What metrics and analytics do I get to measure program effectiveness?",
    answer: "Comprehensive outcome dashboards: (1) Clinical outcomes—pre-post comparison of HbA1c, BP, lipids, kidney function by patient cohort, achievement of clinical targets (% patients with HbA1c <7%), (2) Engagement metrics—enrollment rate, active participation rate, test completion %, consultation adherence %, 6-month and 12-month retention, (3) Utilization analysis—services consumed per patient per month, cost per patient per month, most used services, (4) Patient satisfaction—NPS scores, qualitative feedback, complaints and resolution times, (5) Healthcare cost impact—hospitalization reduction, ER visit reduction, medication adherence savings, total cost of care pre-post program, ROI calculation, (6) Population health trends—distribution of risk levels (low/moderate/high), comorbidity patterns, demographic analysis. Reporting: (1) Real-time dashboards—drill down by condition, geography, risk level, (2) Scheduled reports—weekly/monthly emails with key metrics, (3) Custom reports—export data for internal analytics, regulatory reporting, research publications. Benchmarking: Compare your program performance against national benchmarks and peer programs. Transparent data access—no black box, full visibility into every metric."
  },
  
  // Provider & Quality Management
  {
    question: "How do you ensure quality of doctors in disease-specific care programs?",
    answer: "Rigorous doctor selection: (1) Specialty-specific credentials—diabetologists for diabetes programs, cardiologists for cardiac care, pulmonologists for COPD, psychiatrists for mental health, (2) Experience requirements—minimum 5 years post-residency for chronic disease management, 10+ years for complex conditions, (3) Training—mandatory training on care protocols, platform usage, communication guidelines before onboarding, (4) CSAT monitoring—patient ratings after every consultation, <4.2/5 rating triggers review, (5) Clinical outcome tracking—doctors' patients' outcomes compared to benchmarks (e.g., average HbA1c reduction), underperformers counseled or removed, (6) Peer review—periodic chart reviews by senior clinicians, feedback on clinical decisions, (7) CME requirements—doctors must complete continuing medical education in their specialty annually. Quality assurance: Random consultation recording reviews (with consent), guideline adherence scoring, medication error rates. Doctors consistently below quality thresholds are removed from network. Geographic coverage: Top-tier specialists in metros, experienced generalists + telemedicine specialist support in tier-2/3 cities."
  },
  {
    question: "Do you support home-based care for chronic disease patients who cannot travel?",
    answer: "Comprehensive home care services: (1) Home sample collection—phlebotomist visits for blood tests (quarterly HbA1c, monthly blood sugar for diabetics), convenient for elderly, disabled, or mobility-impaired patients across 9,000+ pincodes, (2) Home nursing visits—vitals monitoring (BP, pulse, oxygen saturation), wound care (diabetic foot ulcers), injection administration (insulin training, vitamin B12 shots), ECG at home, available in metros and tier-2 cities, (3) Physiotherapy at home—post-stroke rehab, joint exercises for arthritis, respiratory exercises for COPD, 1-3 sessions per week, (4) Medication delivery—medicines delivered to doorstep within 6-24 hours, cold chain for insulin/biologics, adherence packaging (dose packs), (5) Teleconsultations—video consults eliminate travel, especially valuable for tier-2/3 cities with limited specialist access, (6) Palliative care—for terminal cancer patients, pain management, psychological support, family counseling. Coordination: All services coordinated via single platform—care manager schedules home visits, tracks completion, ensures continuity. Particularly valuable for: Geriatric patients (70+ age), post-hospitalization recovery, patients with multiple comorbidities, rural/remote patients. Home care reduces patient burden, improves adherence, enables aging in place."
  },
  {
    question: "How does cross-service coordination work to ensure seamless care?",
    answer: "Automated care orchestration: (1) Test → Consult—diabetic patient completes HbA1c test → result shows 8.5% (above target) → system auto-schedules doctor consult within 48 hours → doctor receives pre-consultation summary with trend chart, (2) Consult → Pharmacy—doctor prescribes medication during teleconsult → e-prescription auto-sent to pharmacy → medicines delivered same day → patient receives adherence reminders, (3) Consult → Diagnostics—doctor orders follow-up tests during consultation → test booking link sent to patient via SMS → patient schedules convenient slot, (4) Critical value → Escalation—kidney function shows creatinine 3.5 mg/dL → care manager alerted → nephrologist consult arranged within 24 hours → hospitalization coordinated if needed, (5) Medication non-adherence → Intervention—pharmacy system detects missed refill (patient didn't reorder metformin) → care manager calls to understand barriers → resolve issues (cost, side effects, forgetting), (6) Protocol-driven scheduling—system auto-books next HbA1c test 3 months after last test without manual intervention. Zero manual coordination needed—system manages entire care journey, care managers handle exceptions only. Patient sees seamless experience—all services integrated in single app, unified communication, no redundant paperwork."
  },
  
  // Program Design & ROI
  {
    question: "What is typical ROI for disease management programs?",
    answer: "Financial returns: (1) Direct cost savings—₹8,000-12,000 per patient annually from avoided hospitalizations and ER visits (diabetic without management: ₹25,000-35,000 annual healthcare cost → with management: ₹18,000-22,000), (2) Medication optimization—generic substitution, adherence improvement reduces medication waste, ₹2,000-3,000 savings per patient, (3) Productivity gains—fewer sick days, better work performance, estimated ₹15,000-20,000 value per patient for employers, (4) Program investment—₹6,000-10,000 per patient annually (includes tests, consultations, care management, technology), (5) Net ROI—positive ROI within 12-18 months, 2-3x return over 3 years. ROI varies by: Population risk profile (high-risk populations see faster ROI), baseline healthcare costs (higher baseline = more savings potential), program intensity (more touchpoints = better outcomes but higher cost), engagement levels (90% engagement = optimal ROI, 50% engagement = marginal). Who benefits: Insurers (lower claims), employers (healthier workforce), patients (better health, less OOP), providers (steady revenue). Case example: 10,000-employee corporate with 1,500 diabetic/hypertensive employees → ₹90 lakhs annual program cost → ₹1.2 Cr savings from reduced hospitalizations → ₹30 lakhs net savings + improved employee satisfaction."
  },
  {
    question: "Can I offer disease management programs across multiple cities and states?",
    answer: "Multi-geography program deployment: (1) Centralized management—single platform/dashboard to manage programs across 20+ cities, 10+ states, (2) Local service delivery—diagnostics, consultations, pharmacy delivered locally in 9,000+ pincodes, (3) Standardized protocols—same clinical care pathways applied uniformly across geographies ensuring quality consistency, (4) Regional customization—adjust for local healthcare costs (metro vs tier-2/3 pricing), language preferences (Hindi, Tamil, Telugu, Bengali, Marathi), cultural considerations (dietary advice for diabetics considers regional cuisine), (5) Workforce support—works for corporates with distributed employees (bank branches, retail chains, manufacturing plants across states), government health schemes (state-wide or national programs), insurers with pan-India membership. Example deployments: (1) National insurance company—diabetes program for 50,000 members across 15 states, (2) Large corporate—wellness program for 80,000 employees across 100 office locations, (3) State government—hypertension program for 200,000 beneficiaries across rural and urban areas. Technology enables scale—no need for physical infrastructure in each city, local provider partnerships for last-mile delivery."
  },
  {
    question: "How do you handle patients who are not digitally literate or lack smartphones?",
    answer: "Inclusive program design: (1) Phone-based access—patients can call helpline to book tests, speak to care managers, get test results explained over phone (no app needed), (2) SMS reminders—basic text reminders for test dates, appointment confirmations work on feature phones, (3) Family member enrollment—patient's family member (son/daughter) manages bookings via app on behalf of elderly/non-digital parent, (4) Home visits—care managers visit patient homes for enrollment, explain program, collect consent forms physically, (5) Assisted enrollment—at health camps or clinic visits, staff help patients register and book services, (6) Multilingual support—care managers speak regional languages, IVR in 10+ languages, (7) Paper-based reporting—test reports can be physically delivered/couriered for patients preferring hard copies. Hybrid model essential for: Rural patients, elderly (65+ age), low-income populations, tier-3 cities with lower digital adoption. Technology-assisted but not technology-dependent programs achieve 60-70% engagement even in non-digital populations vs 10-20% for purely digital-only programs. Care manager human touchpoint is critical—builds trust, explains value, resolves barriers."
  }
];
