/**
 * FAQ Data for Healthcare Providers (Labs, Clinics, Pharmacies)
 * Deep dive into onboarding, payments, capacity utilization, quality standards
 */

export const providersFAQs = [
  // Revenue & Business Model
  {
    question: "How does joining Labstack increase my diagnostic center's revenue across cities?",
    answer: "Revenue growth mechanics: (1) Capacity utilization—typical diagnostic centers run at 40-50% capacity (idle mornings, weekdays), Labstack fills gaps with steady B2B demand reaching 60-75% utilization, (2) Volume increase—10,000-50,000 additional tests annually depending on center size and location (metros: 30-50K tests/year, tier-2: 10-20K tests/year), (3) Home collection expansion—90% of our orders are home collection, enables you to serve patients who wouldn't visit center, new revenue stream, (4) Premium test mix—our clients often order comprehensive panels (lipid profiles, thyroid panels, HbA1c) vs walk-ins ordering basic CBC, (5) Geographic expansion—single Bangalore lab serves patients across Bangalore suburbs (Whitefield, Electronic City, HSR Layout, Indiranagar) via home collection, not limited to lab vicinity. Revenue example: 50-test/day lab in Pune—add 15-25 Labstack tests/day → 30-50% revenue increase → ₹40-60 lakhs additional annual revenue. Margins improve 15-25% because: Fixed costs (rent, equipment, staff) already covered, incremental tests have high contribution margins. No CAC—you don't spend on patient acquisition, we bring demand. Works for: NABL-accredited labs in metros and tier-2 cities (Indore, Jaipur, Coimbatore, Kochi, Nagpur, Visakhapatnam, Chandigarh, Lucknow, Bhubaneswar)."
  },
  {
    question: "How does Labstack increase revenue for pharmacies and medicine delivery?",
    answer: "Pharmacy revenue model: (1) Prescription volume—steady stream of e-prescriptions from teleconsultations (10,000-100,000 prescriptions monthly depending on pharmacy scale), (2) Chronic medication focus—diabetes, hypertension, cholesterol medicines generate recurring monthly revenue vs one-time acute prescriptions, (3) Geographic reach—deliver to 18,000+ pincodes even if you're single-location pharmacy, Labstack coordinates delivery logistics, (4) Cashless orders—patients covered by insurance/corporate wellness programs, you get guaranteed payment from enterprises vs individual collections, (5) Specialty medicines—cold chain logistics for insulin, biologics, vaccines that independent pharmacies struggle with. Revenue benchmark: Medium pharmacy in Mumbai—100-200 Labstack orders/month × average order value ₹800-1,200 → ₹80,000-240,000 monthly revenue → ₹10-30 lakhs annual. Margin: 15-20% on branded medicines, 30-40% on generics. Volume scales: Small pharmacies (100-300 orders/month), Medium (300-1,000), Large chains (1,000-10,000+ orders/month). Operational efficiency: (1) Inventory management—predictable demand patterns help stock planning, (2) Payment certainty—15-day payment terms vs 30-90 days with traditional aggregators, (3) Tech platform—our system manages orders, you focus on dispensing and delivery."
  },
  {
    question: "How do doctors increase patient volume and earnings via teleconsultations?",
    answer: "Doctor earning potential: (1) Consultation volume—50-500 teleconsults per month depending on availability and specialty (general physicians: 200-500/month, specialists: 50-150/month due to higher per-consult time), (2) Per-consultation earnings—₹300-500 for GP consults, ₹500-1,000 for specialist consults, ₹1,000-2,000 for super-specialists (cardiologists, endocrinologists, psychiatrists), (3) Flexible hours—consults during clinic idle time (early morning 7-9 AM, late evening 8-10 PM, lunch breaks), weekends, (4) Geographic expansion—serve patients across India from your location, not limited to city/neighborhood, (5) Chronic care programs—recurring consultations with diabetic/hypertensive patients (monthly or quarterly reviews) provide predictable income stream. Earning examples: (1) GP doing 10 consults/day × ₹400 × 25 days = ₹1 lakh/month, (2) Cardiologist doing 5 consults/day × ₹800 × 20 days = ₹80,000/month, (3) Psychiatrist doing 8 consults/day × ₹1,200 × 22 days = ₹2.1 lakhs/month. Time efficiency: Average 15-20 minute consults vs 30-45 minutes in-person (no physical examination time), enables 3-4 consults per hour. No overhead: Zero clinic rent, staff, utilities for teleconsult-only hours. Quality: Patients are real (not just curiosity), come via insurance/corporate programs, follow-up compliance higher."
  },
  
  // Onboarding & Operations
  {
    question: "What is the complete onboarding process for diagnostic labs?",
    answer: "7-step onboarding: (1) Application—submit lab details, NABL certificate, CAP accreditation (if any), owner KYC, bank details, service catalog (pathology/radiology/cardiac tests), (2) Verification—3-5 business days for document checks, NABL validity confirmation, reference checks, (3) Site inspection—virtual inspection via video call for tier-2/3 cities, physical inspection for metros by partner success team (quality of equipment, staff competency, sample storage), (4) Rate card agreement—negotiate pricing for common tests (CBC, lipid profile, HbA1c, etc.), volume-based discounts, home collection charges, (5) Technical integration—train your staff on partner portal (order management, report upload, tracking), LIS integration if applicable via API/HL7, (6) Test orders—5-10 dummy orders to validate workflows (sample collection, testing, report upload, turnaround time), (7) Go-live—approved for production, start receiving real orders, account manager assigned. Timeline: 7-14 days from application to first order. Requirements: (1) NABL/ISO 15189 accreditation mandatory, (2) CAP preferred but not required, (3) Minimum 50 tests/day capacity, (4) Home collection phlebo team (can be your staff or we coordinate), (5) Digital reporting capability (PDF, ideally structured data via LIS). Rejection reasons: NABL expired, poor quality reputation, slow TAT history, high complaint rates. Approval rate: ~85% of applicant labs get approved."
  },
  {
    question: "How quickly do I receive payments for services rendered?",
    answer: "Fast payment cycles: (1) 15-day payment terms—orders completed in month are paid by 15th of next month, (2) Automated reconciliation—invoices generated automatically with line-item breakup (test name, date, patient ID, amount), (3) Direct bank transfer—NEFT/RTGS to your registered bank account, (4) Transparent tracking—partner portal shows pending invoices, paid invoices, payment history, (5) GST invoicing—we handle GST compliance, provide input credit, (6) No TDS deduction—TDS your responsibility as per tax laws, we pay gross amount. Example timeline: Services delivered April 1-30 → Invoice generated May 1 → Payment credited May 15. Compare to: Traditional aggregators (60-90 day cycles), insurance cashless (45-60 days), direct patient billing (immediate but high receivables risk). Dispute resolution: If amount discrepancy, raise ticket, resolved within 48 hours. Payment reliability: 99.8% on-time payment record, funded by top VCs/banks, strong balance sheet. Earning predictability: As order volume stabilizes (3-6 months), monthly revenue becomes predictable, helps with cash flow planning. For large volume providers (10,000+ tests/month), weekly payment cycles negotiable."
  },
  {
    question: "Do I need to invest in expensive technology or software?",
    answer: "Minimal tech investment: (1) Partner portal—free web console for order management, no software purchase, (2) Basic requirements—computer/tablet with internet, printer for labels/reports, WhatsApp-capable phone, (3) Optional LIS integration—if you have lab information system (LabVantage, Agappe, Acculab), we integrate via API/HL7, not mandatory, (4) Phlebotomist app—free mobile app for your home collection staff, tracks GPS, upload sample photos, mark status, (5) Billing integration—if you use accounting software (Tally, Zoho Books), we provide APIs for auto-invoice import. Investment alternatives: (1) No LIS? Use our portal to manually upload reports (PDF upload), (2) No home collection team? We coordinate freelance phlebotomists, deduct costs from your payment, (3) No delivery fleet? We use courier partners for sample transport. Technology support: (1) Training—virtual training sessions for your staff on portal usage (2-3 hours), (2) Onboarding support—dedicated implementation engineer for first month, (3) Ongoing helpline—partner support via phone/WhatsApp 8 AM-8 PM. Cloud-based: Everything web-based, no on-premise servers or IT staff needed. Cost comparison: Traditional aggregators charge ₹50,000-200,000 integration fees, we charge ₹0. Only pay per transaction, no upfront technology cost."
  },
  {
    question: "Can I continue working with my existing clients and platforms?",
    answer: "Non-exclusive partnership: (1) Zero lock-in—continue with 1mg, PharmEasy, Thyrocare, Metropolis partnerships, walk-in patients, direct corporate contracts, (2) Incremental volume—Labstack orders are ADDITIONAL to existing business, fill idle capacity slots, (3) No exclusivity required—we don't demand exclusivity, you're free to work with competitors, (4) Flexible capacity allocation—you control how many slots offered to Labstack vs reserved for other channels, (5) Dynamic pricing—different rates for different channels as per your agreements. Capacity management: Partner portal lets you set daily capacity limits—e.g., max 50 Labstack orders/day, if exceeded, orders routed to alternate labs automatically. Common model: 60% capacity from existing channels (walk-ins, tie-ups) + 40% from Labstack to optimize utilization. No conflicts: Labstack patients are enterprise-driven (insurance, corporate wellness), rarely overlap with your direct walk-in/B2C patients. Exit freedom: Terminate partnership with 30-day notice, no penalties, no long-term contracts. Comparison: Some aggregators demand exclusivity or penalize multi-homing, we encourage diversification for your business resilience."
  },
  
  // Quality & Compliance
  {
    question: "What quality standards do I need to maintain for pathology and radiology?",
    answer: "Quality framework: (1) Accreditation—NABL ISO 15189 mandatory for pathology, AERB approval for radiology, (2) Turnaround time—standard pathology (24-48 hours), radiology reports (24-72 hours), critical values reported within 2 hours, (3) Report quality—radiologist-signed reports for imaging, pathologist review for abnormal values, proper formatting, no spelling errors, (4) Sample collection standards—trained phlebotomists (certification required), proper PPE, sample labeling with barcodes, cold chain for specific tests, (5) Proficiency testing—participate in NABL/CAP proficiency programs, maintain passing scores. Ongoing monitoring: (1) Customer satisfaction (CSAT)—patients rate service after every order (sample collection, TAT, report quality), target >4.2/5, (2) TAT compliance—% orders delivered within promised TAT, target >95%, (3) Rejection rate—% samples rejected due to hemolysis, clotting, incorrect collection, target <2%, (4) Complaint rate—patient complaints per 1,000 orders, target <5, (5) Audit scores—quarterly quality audits by our team, 100-point checklist, target >85. Quality improvement: We provide feedback reports monthly showing your performance vs network benchmarks, areas for improvement. Non-compliance consequences: (1) Coaching—if CSAT <4.0, audit score <80, we provide training and action plan, (2) Warning—repeated issues get formal warning, (3) Suspension—serious violations (fake reports, using non-NABL labs, major breaches) result in immediate suspension, (4) Termination—persistent quality issues or fraud lead to permanent removal. 95% providers maintain quality standards consistently."
  },
  {
    question: "What happens if I cannot fulfill an order due to equipment breakdown or staff shortage?",
    answer: "Graceful failure handling: (1) Immediate notification—inform via partner portal (mark order 'unable to fulfill') within 1 hour of receiving order, (2) Reason documentation—specify why (equipment maintenance, power outage, staff unavailable, sample volume too high), (3) Automatic rerouting—system instantly assigns order to next available lab in same area, (4) Patient communication—patient notified of change, new appointment scheduled if home collection affected, (5) No financial penalty—genuine equipment issues, emergency staff leave, natural calamities exempted from SLA penalties. Planned downtime: (1) Advance notice—if equipment maintenance scheduled, block your calendar 3-7 days ahead in portal, (2) Temporary capacity reduction—reduce daily limits during staff shortage (e.g., 100 orders/day → 50/day), (3) Partial services—disable specific tests while others remain active (e.g., radiology down, pathology continues). Frequent failures impact: (1) Ranking—repeated cancellations lower your rank in provider selection algorithm, fewer future orders, (2) Investigation—if pattern detected (every weekend, specific time slots), partner success manager investigates for systematic issues, (3) Performance review—chronic unreliability leads to warning → probation → termination if unresolved. Acceptable failure rate: <3% order cancellations acceptable (industry standard 5-8%), proactive communication is key. Emergency support: If truly force majeure (floods, riots, power grid failure for days), we work with you on solution, don't penalize."
  },
  {
    question: "How does Labstack ensure providers are paid fairly and prevent exploitation?",
    answer: "Provider-friendly commercial model: (1) Market-rate pricing—rates negotiated based on regional benchmarks, not race-to-bottom like some aggregators, (2) Transparent pricing—every test has defined rate, no hidden deductions, (3) Volume bonuses—achieve monthly targets (e.g., 1,000 tests/month) → 5-10% bonus on next month's orders, (4) Fuel surcharge—home collection charges revised quarterly based on fuel prices, (5) No commission creep—your rates locked for 12 months, annual reviews only, maximum 5% reduction even if market rates drop. Protection from exploitation: (1) Written contracts—all terms clearly documented, no verbal promises, (2) Dispute escalation—if payment issue, commercial conflict, raise to partner success director → VP partnerships → CEO escalation path, (3) Provider NPS surveys—quarterly anonymous feedback from providers about Labstack experience, complaints investigated, (4) Provider advisory board—top 20 providers get seat in quarterly advisory board, influence product/policy decisions. Payment security: (1) Funded by reputed investors (Accel, Sequoia-backed founders), (2) Separate escrow accounts for provider payments, (3) Insurance coverage for business continuity. Comparison: Traditional aggregators take 30-40% platform fees, delay payments 60-90 days, change rates without notice. We charge 15-25%, pay in 15 days, respect provider economics."
  },
  
  // Network & Geographic Coverage
  {
    question: "Do you provide marketing to drive direct B2C demand to my center?",
    answer: "B2B infrastructure only: (1) No B2C marketing—we don't advertise to consumers, no brand campaigns, no patient-facing app in app stores, (2) Pure enterprise demand—orders come from our B2B clients (insurers, corporates, healthtech platforms), (3) Labstack invisible—patients don't know Labstack exists, they interact with enterprise's brand, you fulfill orders, (4) White-label model—you're infrastructure provider, not consumer-facing brand. Your value: (1) Consistent B2B volume—10,000-50,000 annual orders without any marketing investment from you, (2) Zero CAC—no customer acquisition cost, we bring demand, you fulfill, (3) Capacity utilization—fill your idle mornings, weekdays, slots that walk-ins don't fill, (4) Predictable revenue—enterprise contracts = steady monthly volumes vs unpredictable walk-in traffic. Business model fit: Ideal for: (1) Labs wanting to increase utilization without marketing spend, (2) Pharmacies preferring steady enterprise demand over retail volatility, (3) Doctors willing to do teleconsults but not wanting to build patient base themselves. Not ideal for: Providers seeking direct patient relationships, brand building, premium positioning need different strategy. Think of it like: Hotel partnering with OYO (B2B demand, no direct branding) vs running own website/advertising (B2C demand, full brand control). Most providers do both—Labstack for capacity filling + own marketing for brand building."
  },
  {
    question: "Which cities and geographies do you prioritize for provider onboarding?",
    answer: "Geographic prioritization: (1) Metros—highest demand, continuous onboarding in Mumbai (Andheri, Bandra, Powai, Thane, Navi Mumbai), Delhi NCR (Delhi, Gurgaon, Noida, Faridabad, Ghaziabad), Bangalore (Whitefield, Electronic City, HSR Layout, Indiranagar, Jayanagar), Hyderabad (Banjara Hills, Gachibowli, Madhapur, Secunderabad), Chennai (T Nagar, Velachery, OMR, Guindy), Pune (Koregaon Park, Hinjewadi, Viman Nagar), Kolkata (Salt Lake, New Town, Rajarhat), (2) Tier-2 cities—actively recruiting in Indore, Jaipur, Chandigarh, Lucknow, Coimbatore, Kochi, Nagpur, Visakhapatnam, Bhubaneswar, Vadodara, Rajkot, Surat, Nashik, Aurangabad, Mysore, Mangalore, Ludhiana, Amritsar, (3) Tier-3 cities—selective onboarding in Guntur, Vijayawada, Ranchi, Raipur, Dehradun, Gorakhpur, Varanasi, Siliguri, Guwahati where demand exists. Network density targets: Metros need 50-100 partner labs (competition + redundancy), tier-2 cities need 10-25 labs, tier-3 cities need 3-8 labs. Provider selection: Quality over quantity—better to have 5 excellent labs than 50 mediocre ones. Application priority: (1) NABL accreditation, (2) CAP/ISO 15189, (3) Existing capacity, (4) Technology readiness, (5) Geographic gap filling. If you're in under-served geography (tier-3 city, suburban pincode), faster approval despite smaller scale."
  },
  {
    question: "Can I set capacity limits or blackout dates when I'm unavailable?",
    answer: "Full capacity control: (1) Daily limits—set maximum orders/day (e.g., 50 pathology tests, 10 radiology scans), system auto-stops bookings once reached, (2) Hourly slots—for home collection, define available time slots (8-10 AM, 10-12 PM, 4-6 PM), patients book within these, (3) Blackout dates—block specific dates for holidays, equipment maintenance, staff training (Diwali, Christmas, annual shutdown), (4) Service-specific limits—enable/disable specific tests (e.g., disable MRI for 1 week while machine servicing, keep pathology active), (5) Emergency pause—instant 'pause all orders' button if sudden emergency, reactivate when ready. Advance planning: (1) Recurring blocks—set annual pattern (closed every Sunday, reduced capacity in summers), (2) Notification to Labstack—we reroute orders to backup providers, no patient impact, (3) Capacity forecasting—we share expected order volumes 7 days ahead, you adjust capacity accordingly. Use cases: (1) Seasonal variations—reduce capacity during monsoons (road conditions affect home collection), increase during flu season (high demand), (2) Staff planning—if 2 phlebotomists on leave, reduce home collection slots, (3) Equipment maintenance—radiology machines need annual servicing, block 2-3 days ahead. System intelligence: If you're frequently at capacity, we recommend capacity increase (hire more staff, equipment) or help recruit additional provider in your area to share load. Partner portal: Real-time dashboard shows current capacity utilization, bookings for next 7 days, ability to adjust instantly."
  },
  {
    question: "How do you ensure I get quality orders and not just low-margin business?",
    answer: "Profitable order mix: (1) Enterprise pricing—our clients are insurers, corporates, healthtech platforms with better realization than Groupon-style discount platforms, (2) Test mix—focus on routine preventive tests (HbA1c, lipid profiles, thyroid, vitamin D) and chronic disease monitoring, not just basic CBC, (3) Volume discounts—yes, but not predatory (10-15% below walk-in rates vs 40-50% on discount platforms), (4) Home collection premium—you charge ₹50-100 home visit fee, 90% of orders are home collection, adds revenue, (5) No patient acquisition cost—you don't spend on marketing, higher margin vs orders from Google Ads. Pricing philosophy: Sustainable partnerships over extractive aggregation. We want providers profitable so they maintain quality and stay long-term. Provider economics: Average diagnostic test—you earn ₹300-800 per test (CBC ₹200-300, HbA1c ₹400-600, lipid profile ₹500-800, vitamin D ₹800-1,200) vs walk-in (₹400-1,000 with marketing cost ₹50-100 = net ₹350-900), Labstack comparable or slightly lower but zero CAC. Consultation rates: Doctors earn ₹300-1,000 per teleconsult, comparable to OPD visit (₹500-1,500 minus clinic overhead ₹100-300 = net ₹400-1,200). Pharmacy margins: 15-20% on branded, 30-40% on generics, same as retail. Order quality: Real patients with genuine medical needs (insurance/employer-sponsored), not deal-seekers, better compliance, lower cancellation rates (3% vs 15% on discount platforms)."
  }
];
